-- Default setting values (USER_CONFIG) and storage key names (SETTINGS).

local USER_CONFIG = {
    DARK_MODE                = false,
    MONOCHROME               = false,

    SHOW_BOOK                = true,
    SHOW_CHAP                = true,
    SHOW_GOAL                = true,
    SHOW_BATT                = true,
    SHOW_MSG                 = true,
    SECTION_ORDER            = { "book", "chapter", "goal", "battery", "message" },
    SHOW_BOOK_AUTHOR         = false,
    SHOW_BOOK_SERIES         = false,
    SHOW_BOOK_PAGES          = false,
    SHOW_BOOK_TIME_REMAINING = true,
    SHOW_BOOK_PERCENTAGE     = true,
    SHOW_CHAP_COUNT          = false,
    SHOW_CHAP_PAGES          = false,
    SHOW_CHAP_TIME_REMAINING = true,
    SHOW_CHAP_PERCENTAGE     = true,
    DAILY_GOAL               = 50,
    GOAL_TYPE                = "pages",
    DAILY_GOAL_MINUTES       = 30,
    SHOW_GOAL_STREAK         = false,
    SHOW_GOAL_ACHIEVEMENT    = false,
    SHOW_GOAL_PAGES          = true,
    SHOW_GOAL_PERCENTAGE     = true,
    GOAL_TITLE_TYPE          = "time",
    SHOW_BATT_RATE           = false,
    SHOW_BATT_TIME           = true,
    SHOW_BATT_CLOCK          = true,
    SHOW_BATT_DATE           = false,
    MESSAGE_SOURCE           = "highlight",
    MSG_HEADER               = "Highlights",
    CUSTOM_MESSAGE           = "Books are a uniquely portable magic.",
    MAX_HIGHLIGHT_LENGTH     = 200,
    HIGHLIGHT_ADD_QUOTES     = true,
    SHOW_HIGHLIGHT_LOCATION  = false,
    SHOW_QUOTE_ATTRIBUTION   = false,
    SHOW_MSG_HEADER          = true,

    SECTION_GAPS_ENABLED     = false,
    SECTION_GAP_SIZE         = 20,
    POS                      = "center",
    POS_OFFSET_X             = 0,
    POS_OFFSET_Y             = 0,
    BOX_WIDTH_PCT            = 60,
    OPACITY                  = 204,
    BORDER_SIZE              = 0,
    BORDER_SIZE_2            = 0,
    SECTION_RADIUS           = 0,
    BAR_INLINE               = false,
    BAR_INLINE_WIDTH_PCT     = 100,
    BAR_BORDER_SIZE          = 0,
    SECTION_PADDING          = 12,
    SECTION_PADDING_TOP      = 12,
    SECTION_PADDING_BOTTOM   = 12,
    SECTION_PADDING_LEFT     = 12,
    SECTION_PADDING_RIGHT    = 12,
    ICON_TEXT_GAP            = 16,
    SLEEP_ORIENTATION        = "auto",
    ANTI_GHOSTING_FLASH      = false,

    COLOR_BOOK_FILL          = "#82A9D9",
    COLOR_CHAPTER_FILL       = "#F2C2CF",
    COLOR_GOAL_FILL          = "#F9E480",
    BATT_HIGH_COLOR          = "#A1D9A3",
    BATT_MED_COLOR           = "#FDCB92",
    BATT_LOW_COLOR           = "#FF9B9B",
    BATT_CHARGING_COLOR      = "#82CFFF",
    COLOR_MESSAGE_FILL       = "#99A7D9",
    COLOR_LIGHT              = "#000000",
    COLOR_DARK               = "#ffffff",
    ICON_USE_BAR_COLOR       = true,
    ICON_SET                 = "Default",
    ICON_SIZE                = 40,
    BAR_HEIGHT               = 12,
    SHOW_ICONS               = true,
    SHOW_BARS                = true,

    FONT_FACE_TITLE          = "Zilla Slab",
    FONT_SIZE_TITLE          = 10,
    FONT_FACE_SUBTITLE       = "Zilla Slab",
    FONT_SIZE_SUBTITLE       = 9,
    TEXT_ALIGN               = "left",
    BOOK_MULTILINE           = true,
    CHAP_MULTILINE           = true,
    CLEAN_CHAP               = true,
    ALL_TITLES_BOLD          = false,

    BG_DIMMING               = 128,
    BG_DIMMING_COLOR         = "#000000",
    BG_TYPE                  = "cover",
    BG_FOLDER                = "",
    BG_IMAGE_PATH            = "",
    BG_SOLID_COLOR           = "#2C3E50",
    BG_STRETCH               = true,
    EXCLUDED_COVER_BG_TYPE   = "transparent",
    EXCLUDED_HIDE_BOOK_INFO  = true,
    BG_COVER_FILL_COLOR      = "black",
    BG_COVER_ALIGN           = "center",

    SHOW_IN_FILEMANAGER      = true,
    HIDE_PRELOADED_PRESETS   = false,
    BATT_STAT_TYPE           = "awake",
    BATT_MANUAL_RATE         = 2.5,
    MSG_SHOW_FULL_BAR        = false,
    GOAL_STAT_SCOPE          = "all",
    EXPORT_PATH              = "",
    EXPORT_ENABLED           = false,
    EXPORT_FILENAME          = "screensaver",
    EXPORT_FORMAT            = "png",

    COLOR_BOX_BG             = "#FFFFFF",
    COLOR_BOX_BG_DARK        = "#000000",
    COLOR_TEXT               = "#000000",
    COLOR_TEXT_DARK          = "#FFFFFF",

    COVER_IN_BOOK            = false,
    COVER_SIZE               = 120,
    COVER_BORDER_SIZE        = 0,
    COVER_ALIGN_TO_TEXT      = false,
}

local SETTINGS = {
    TYPE                     = "screensaver_type",
    SHOW_MSG_GLOBAL          = "screensaver_show_message",
    MSG_TEXT                 = "screensaver_message",

    VERSION                  = "customisable_ss_version",
    LAST_BOOK_STATE          = "customisable_ss_last_book_state",

    DARK_MODE                = "customisable_ss_dark_mode",
    MONOCHROME               = "customisable_ss_monochrome",

    SHOW_BOOK                = "customisable_ss_show_book",
    SHOW_CHAP                = "customisable_ss_show_chap",
    SHOW_GOAL                = "customisable_ss_show_goal",
    SHOW_BATT                = "customisable_ss_show_batt",
    SHOW_MSG                 = "customisable_ss_show_message",
    SECTION_ORDER            = "customisable_ss_section_order",
    SHOW_BOOK_AUTHOR         = "customisable_ss_show_book_author",
    SHOW_BOOK_SERIES         = "customisable_ss_show_book_series",
    SHOW_BOOK_PAGES          = "customisable_ss_show_book_pages",
    SHOW_BOOK_TIME_REMAINING = "customisable_ss_show_book_time_remaining",
    SHOW_BOOK_PERCENTAGE     = "customisable_ss_show_book_percentage",
    SHOW_CHAP_COUNT          = "customisable_ss_show_chap_count",
    SHOW_CHAP_PAGES          = "customisable_ss_show_chap_pages",
    SHOW_CHAP_TIME_REMAINING = "customisable_ss_show_chap_time_remaining",
    SHOW_CHAP_PERCENTAGE     = "customisable_ss_show_chap_percentage",
    DAILY_GOAL               = "customisable_ss_daily_goal",
    GOAL_TYPE                = "customisable_ss_goal_type",
    DAILY_GOAL_MINUTES       = "customisable_ss_daily_goal_minutes",
    SHOW_GOAL_STREAK         = "customisable_ss_show_goal_streak",
    SHOW_GOAL_ACHIEVEMENT    = "customisable_ss_show_goal_achievement",
    SHOW_GOAL_PAGES          = "customisable_ss_show_goal_pages",
    SHOW_GOAL_PERCENTAGE     = "customisable_ss_show_goal_percentage",
    GOAL_TITLE_TYPE          = "customisable_ss_goal_title_type",
    SHOW_BATT_DATE           = "customisable_ss_show_batt_date",
    SHOW_BATT_RATE           = "customisable_ss_show_batt_rate",
    SHOW_BATT_TIME           = "customisable_ss_show_batt_time",
    SHOW_BATT_CLOCK          = "customisable_ss_show_batt_clock",
    MESSAGE_SOURCE           = "customisable_ss_message_source",
    MSG_HEADER               = "customisable_ss_message_header",
    CUSTOM_MESSAGE           = "customisable_ss_custom_message",
    MAX_HIGHLIGHT_LENGTH     = "customisable_ss_max_highlight_length",
    HIGHLIGHT_ADD_QUOTES     = "customisable_ss_highlight_add_quotes",
    SHOW_HIGHLIGHT_LOCATION  = "customisable_ss_show_highlight_location",
    SHOW_QUOTE_ATTRIBUTION   = "customisable_ss_show_quote_attribution",
    SHOW_MSG_HEADER          = "customisable_ss_show_msg_header",

    SECTION_GAPS_ENABLED     = "customisable_ss_section_gaps_enabled",
    SECTION_GAP_SIZE         = "customisable_ss_section_gap_size",
    POS                      = "customisable_ss_position",
    POS_OFFSET_X             = "customisable_ss_pos_offset_x",
    POS_OFFSET_Y             = "customisable_ss_pos_offset_y",
    BOX_WIDTH_PCT            = "customisable_ss_box_width_pct",
    OPACITY                  = "customisable_ss_opacity",
    BORDER_SIZE              = "customisable_ss_border_size",
    BORDER_SIZE_2            = "customisable_ss_border_size_2",
    SECTION_RADIUS           = "customisable_ss_section_radius",
    BAR_INLINE               = "customisable_ss_bar_inline",
    BAR_INLINE_WIDTH_PCT     = "customisable_ss_bar_inline_width_pct",
    BAR_BORDER_SIZE          = "customisable_ss_bar_border_size",
    SECTION_PADDING          = "customisable_ss_section_padding",
    SECTION_PADDING_TOP      = "customisable_ss_section_padding_top",
    SECTION_PADDING_BOTTOM   = "customisable_ss_section_padding_bottom",
    SECTION_PADDING_LEFT     = "customisable_ss_section_padding_left",
    SECTION_PADDING_RIGHT    = "customisable_ss_section_padding_right",
    ICON_TEXT_GAP            = "customisable_ss_icon_text_gap",
    SLEEP_ORIENTATION        = "customisable_ss_sleep_orientation",
    ANTI_GHOSTING_FLASH      = "customisable_ss_anti_ghosting_flash",

    COLOR_BOOK_FILL          = "customisable_ss_color_book",
    COLOR_CHAPTER_FILL       = "customisable_ss_color_chapter",
    COLOR_GOAL_FILL          = "customisable_ss_color_goal",
    BATT_HIGH_COLOR          = "customisable_ss_batt_high",
    BATT_MED_COLOR           = "customisable_ss_batt_med",
    BATT_LOW_COLOR           = "customisable_ss_batt_low",
    BATT_CHARGING_COLOR      = "customisable_ss_batt_charging",
    COLOR_MESSAGE_FILL       = "customisable_ss_color_message",
    COLOR_DARK               = "customisable_ss_color_dark",
    COLOR_LIGHT              = "customisable_ss_color_light",
    ICON_USE_BAR_COLOR       = "customisable_ss_icon_use_bar_color",
    ICON_SET                 = "customisable_ss_icon_set",
    ICON_SIZE                = "customisable_ss_icon_size",
    BAR_HEIGHT               = "customisable_ss_bar_height",
    SHOW_ICONS               = "customisable_ss_show_icons",
    SHOW_BARS                = "customisable_ss_show_bars",

    FONT_FACE_TITLE          = "customisable_ss_font_face_title",
    FONT_SIZE_TITLE          = "customisable_ss_font_size_title",
    FONT_FACE_SUBTITLE       = "customisable_ss_font_face_subtitle",
    FONT_SIZE_SUBTITLE       = "customisable_ss_font_size_subtitle",
    TEXT_ALIGN               = "customisable_ss_text_align",
    BOOK_MULTILINE           = "customisable_ss_book_multiline",
    CHAP_MULTILINE           = "customisable_ss_chap_multiline",
    CLEAN_CHAP               = "customisable_ss_clean_chapters",
    ALL_TITLES_BOLD          = "customisable_ss_all_titles_bold",

    BG_DIMMING               = "customisable_ss_bg_dimming",
    BG_DIMMING_COLOR         = "customisable_ss_bg_dimming_color",
    BG_TYPE                  = "customisable_ss_bg_type",
    BG_FOLDER                = "customisable_ss_bg_folder",
    BG_IMAGE_PATH            = "customisable_ss_bg_image_path",
    BG_SOLID_COLOR           = "customisable_ss_bg_solid_color",
    BG_STRETCH               = "customisable_ss_bg_stretch",
    BG_COVER_FILL_COLOR      = "customisable_ss_bg_cover_fill_color",
    BG_COVER_ALIGN           = "customisable_ss_bg_cover_align",
    EXCLUDED_COVER_BG_TYPE   = "customisable_ss_excluded_cover_bg_type",
    EXCLUDED_HIDE_BOOK_INFO  = "customisable_ss_excluded_hide_book_info",

    PRESETS                  = "customisable_ss_presets",
    CYCLE_INDEX              = "customisable_ss_presets_cycle_index",
    LAST_LOADED_PRESET       = "customisable_ss_last_loaded_preset",
    SHOW_IN_FILEMANAGER      = "customisable_ss_show_in_filemanager",
    HIDE_PRELOADED_PRESETS   = "customisable_ss_hide_preloaded_presets",
    BATT_STAT_TYPE           = "customisable_ss_batt_stat_type",
    BATT_MANUAL_RATE         = "customisable_ss_batt_manual_rate",
    MSG_SHOW_FULL_BAR        = "customisable_ss_msg_show_full_bar",
    GOAL_STAT_SCOPE          = "customisable_ss_goal_stat_scope",
    EXPORT_PATH              = "customisable_ss_export_path",
    EXPORT_ENABLED           = "customisable_ss_export_enabled",
    EXPORT_FILENAME          = "customisable_ss_export_filename",
    EXPORT_FORMAT            = "customisable_ss_export_format",

    COLOR_BOX_BG             = "customisable_ss_color_box_bg",
    COLOR_BOX_BG_DARK        = "customisable_ss_color_box_bg_dark",
    COLOR_TEXT               = "customisable_ss_color_text",
    COLOR_TEXT_DARK          = "customisable_ss_color_text_dark",

    COVER_IN_BOOK            = "customisable_ss_cover_in_book",
    COVER_SIZE               = "customisable_ss_cover_size",
    COVER_BORDER_SIZE        = "customisable_ss_cover_border_size",
    COVER_ALIGN_TO_TEXT      = "customisable_ss_cover_align_to_text",
}

local function getSetting(key)
    local value = require("css_settings").plugin():readSetting(SETTINGS[key])
    if value == nil then return USER_CONFIG[key] end
    return value
end

return {
    USER_CONFIG = USER_CONFIG,
    SETTINGS    = SETTINGS,
    getSetting  = getSetting,
}
